import assert from "node:assert/strict";
import { scoreSleeperProjection } from "../src/lib/core/playerScoring.ts";
import { normalizeWeeklyPlayerRows } from "../src/lib/platforms/sleeper/playerStats.ts";
import { normalizeMatchups } from "../src/lib/platforms/sleeper/normalize.ts";
const row = { player_id: "1", season: "2026", week: 2, season_type: "regular", stats: { rec: 4, rec_yd: 60, rec_td: 1, pts_ppr: 16 } };
assert.equal(scoreSleeperProjection(row.stats, { rec: 0.5, rec_yd: 0.1, rec_td: 6 }, "WR").points, 14);
assert.equal(scoreSleeperProjection({ pass_int: 2 }, { pass_int: -1 }, "QB").points, -2);
assert.deepEqual(scoreSleeperProjection(row.stats, { pts_allow_0: 10 }, "WR").unavailableKeys, []);
assert.deepEqual(scoreSleeperProjection({}, { pts_allow_0: 10 }, "DEF").unavailableKeys, ["pts_allow_0"]);
assert.deepEqual(scoreSleeperProjection({ pts_allow_14_20: 1 }, { pts_allow_0: 10, pts_allow_14_20: 1 }, "DEF"), { points: 1, unavailableKeys: [] });
assert.equal(normalizeWeeklyPlayerRows([row], "2026", 2)["1"].stats.rec, 4);
assert.throws(() => normalizeWeeklyPlayerRows([row], "2025", 2));
assert.throws(() => normalizeWeeklyPlayerRows([row, row], "2026", 2));
assert.throws(() => normalizeWeeklyPlayerRows([{ ...row, stats: { rec: "4" } }], "2026", 2));
const match = normalizeMatchups([{ roster_id: 1, matchup_id: 1, points: 0, players_points: { "1": 0, "2": -1 } }], 2)[0];
assert.equal(match.playerPoints?.["1"], 0);
assert.equal(match.playerPoints?.["2"], -1);
assert.equal(match.playerPoints?.["3"], undefined);
console.log("12 player stats checks passed");
